name: lockout
description: "Open-source NFC app blocker. No Play Services. Works on microG."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_nfc_kit: ^3.5.2
  ndef: ^0.3.3
  shared_preferences: ^2.5.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
